version: '3.8'

services:
  backend:
    build: ./backend
    image: dharshan2208/4bits-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    image: dharshan2208/4bits-frontend:latest
    ports:
      - "5173:80"
    restart: always
    depends_on:
      - backend

  whatsapp:
    build: ./whatsapp
    image: dharshan2208/4bits-whatsapp:latest
    ports:
      - "3001:3001"
      - "5000:5000"
    env_file:
      - ./whatsapp/.env
    volumes:
      - ./whatsapp/whatsapp_cache:/app/whatsapp_cache
    restart: always
